server:
  port: 8080
spring:
  resources:
    static-locations: /META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:D:/tupian
  mvc:
      static-path-pattern: /**


